# -*- coding: utf-8 -*-
"""ternarybertnew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvjH4zHhHauCeecBdReXfASAXWMdDEqU
"""

# ============================================================
# CELL 1 — TernaryBERT pipeline: data prep + fine-tune + quantize
# Official Huawei repo (github.com/huawei-noah/Pretrained-Language-Model).
# Verified against actual repo source (utils_glue.py processors,
# quant_task_glue.py argparse + internals, modeling_quant.py classes).
#
# Supports 8 of 9 GLUE tasks. WNLI excluded: the official script has no
# WnliProcessor (confirmed by reading utils_glue.py/quant_task_glue.py) —
# this matches the original TernaryBERT paper, which also excludes WNLI.
#
# Resumable: re-run this same cell after any disconnect. Completed work
# is skipped automatically via checkpoint-existence checks.
#
# Framework: PyTorch + HuggingFace Transformers
# Training config (applied uniformly to all GLUE tasks):
#   Tasks:              All 8 GLUE tasks (WNLI excluded per official script)
#   Seeds:              42  (random, numpy, torch, CUDA)
#   Optimizer:          AdamW
#   Weight decay:       0.01
#   Batch size:         16
#   Learning rate:      2e-5
#   Warmup ratio:       10%  (num_warmup_steps = 0.10 × total_steps)
#   LR scheduler:       Linear decay (get_linear_schedule_with_warmup)
#   Epochs:             5
#   Max sequence len:   128
# ============================================================

import os, sys, subprocess, time, json, csv, gc, random
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

PROJECT_ROOT = "/content/drive/MyDrive/ternarybert_glue"
for sub in ["data", "finetuned_models", "ternary_models", "results", "logs"]:
    os.makedirs(f"{PROJECT_ROOT}/{sub}", exist_ok=True)

REPO_DIR = "/content/Pretrained-Language-Model"
TB_DIR = f"{REPO_DIR}/TernaryBERT"
if not os.path.exists(TB_DIR):
    subprocess.run(f"git clone https://github.com/huawei-noah/Pretrained-Language-Model.git {REPO_DIR}", shell=True)

os.system("pip install -q datasets transformers torch scipy scikit-learn")

from datasets import load_dataset
import torch
from transformers import (
    BertTokenizer, BertForSequenceClassification,
    get_linear_schedule_with_warmup
)
from torch.utils.data import DataLoader, RandomSampler

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if device.type != "cuda":
    print("⚠️  No GPU detected — go to Runtime > Change runtime type > GPU before proceeding.")

# ------------------------------------------------------------
# REPRODUCIBILITY — seed everything to 42 before any data or model work
# ------------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
print(f"Global seed set to {SEED}")

# ------------------------------------------------------------
# TRAINING HYPERPARAMETERS (applied uniformly across all tasks)
# ------------------------------------------------------------
LEARNING_RATE   = 2e-5
WEIGHT_DECAY    = 0.01
BATCH_SIZE      = 16
NUM_EPOCHS      = 5
MAX_SEQ_LEN     = 128
WARMUP_RATIO    = 0.10   # 10% of total training steps

# ------------------------------------------------------------
# DATA PREP: TSVs at {data_dir}/{lowercase_task}/, exact column layout
# verified from utils_glue.py's real Processor classes.
# ------------------------------------------------------------

DATA_ROOT = f"{PROJECT_ROOT}/data"

def w(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        csv.writer(f, delimiter="\t").writerows(rows)

def gen_sst2():
    d = f"{DATA_ROOT}/sst-2"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "sst2")
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["sentence", "label"]] + [[ex["sentence"], ex["label"]] for ex in ds[split]]
        w(f"{d}/{name}.tsv", rows)

def gen_mrpc():
    d = f"{DATA_ROOT}/mrpc"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "mrpc")
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["Quality", "#1 ID", "#2 ID", "#1 String", "#2 String"]]
        for ex in ds[split]:
            rows.append([ex["label"], 0, 0, ex["sentence1"], ex["sentence2"]])
        w(f"{d}/{name}.tsv", rows)

def gen_cola():
    d = f"{DATA_ROOT}/cola"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "cola")
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["dummy_src", ex["label"], "dummy_note", ex["sentence"]] for ex in ds[split]]
        w(f"{d}/{name}.tsv", rows)  # NO header row -- matches real CoLA processor

def gen_stsb():
    d = f"{DATA_ROOT}/sts-b"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "stsb")
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["c0","c1","c2","c3","c4","c5","c6","sentence1","sentence2","label"]]
        for ex in ds[split]:
            rows.append([0,0,0,0,0,0,0, ex["sentence1"], ex["sentence2"], ex["label"]])
        w(f"{d}/{name}.tsv", rows)

def gen_qqp():
    d = f"{DATA_ROOT}/qqp"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "qqp")
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["id","qid1","qid2","question1","question2","is_duplicate"]]
        for ex in ds[split]:
            rows.append([0, 0, 0, ex["question1"], ex["question2"], ex["label"]])
        w(f"{d}/{name}.tsv", rows)

def gen_qnli():
    d = f"{DATA_ROOT}/qnli"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "qnli")
    label_map = {0: "entailment", 1: "not_entailment"}
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["index","question","sentence","label"]]
        for ex in ds[split]:
            rows.append([0, ex["question"], ex["sentence"], label_map[ex["label"]]])
        w(f"{d}/{name}.tsv", rows)

def gen_rte():
    d = f"{DATA_ROOT}/rte"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "rte")
    label_map = {0: "entailment", 1: "not_entailment"}
    for split, name in [("train","train"), ("validation","dev")]:
        rows = [["index","sentence1","sentence2","label"]]
        for ex in ds[split]:
            rows.append([0, ex["sentence1"], ex["sentence2"], label_map[ex["label"]]])
        w(f"{d}/{name}.tsv", rows)

def gen_mnli():
    d = f"{DATA_ROOT}/mnli"
    if os.path.exists(f"{d}/train.tsv"): return
    ds = load_dataset("glue", "mnli")
    label_map = {0: "entailment", 1: "neutral", 2: "contradiction"}
    for split, name, fname in [("train","train","train.tsv"), ("validation_matched","dev_matched","dev_matched.tsv")]:
        rows = [["index","c1","c2","c3","c4","c5","c6","c7","sentence1","sentence2","label"]]
        for ex in ds[split]:
            rows.append([0,0,0,0,0,0,0,0, ex["premise"], ex["hypothesis"], label_map[ex["label"]]])
        w(f"{d}/{fname}", rows)

print("Generating TSVs (skips tasks already prepared in Drive)...")
for fn in [gen_sst2, gen_mrpc, gen_cola, gen_stsb, gen_qqp, gen_qnli, gen_rte, gen_mnli]:
    fn()
print("✅ Data prep done.\n")

# ------------------------------------------------------------
# STAGE A: fine-tune standard BERT-base per task with HuggingFace
# `transformers`, saved in the exact format quant_task_glue.py expects
# to load as teacher+student init: {model_dir}/{task_name}/.
# ------------------------------------------------------------

MODEL_DIR_ROOT = f"{PROJECT_ROOT}/finetuned_models"

TASK_HF_MAP = {
    "cola":  ("cola", 2, False, ("sentence", None)),
    "mnli":  ("mnli", 3, False, ("premise", "hypothesis")),
    "mrpc":  ("mrpc", 2, False, ("sentence1", "sentence2")),
    "sst-2": ("sst2", 2, False, ("sentence", None)),
    "sts-b": ("stsb", 1, True,  ("sentence1", "sentence2")),
    "qqp":   ("qqp", 2, False, ("question1", "question2")),
    "qnli":  ("qnli", 2, False, ("question", "sentence")),
    "rte":   ("rte", 2, False, ("sentence1", "sentence2")),
}

def finetune_bert_base(task_name):
    out_dir = f"{MODEL_DIR_ROOT}/{task_name}"
    if os.path.exists(f"{out_dir}/pytorch_model.bin"):
        print(f"  [{task_name}] fine-tuned checkpoint already exists, skipping.")
        return
    hf_name, num_labels, is_regression, (k1, k2) = TASK_HF_MAP[task_name]
    print(f"  [{task_name}] Fine-tuning BERT-base ({hf_name})...")

    ds = load_dataset("glue", hf_name)
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)
    model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased", num_labels=num_labels,
        problem_type="regression" if is_regression else "single_label_classification"
    ).to(device)

    max_len = MAX_SEQ_LEN   # uniform 128 for all tasks
    bsz     = BATCH_SIZE    # uniform 16 for all tasks

    def tokenize_batch(batch):
        if k2 is None:
            return tokenizer(batch[k1], truncation=True, max_length=max_len, padding="max_length")
        return tokenizer(batch[k1], batch[k2], truncation=True, max_length=max_len, padding="max_length")

    train_ds = ds["train"].map(tokenize_batch, batched=True)
    cols = ["input_ids", "attention_mask", "token_type_ids", "label"]
    train_ds.set_format(type="torch", columns=[c for c in cols if c in train_ds.column_names])

    # Use a seeded sampler for reproducible shuffling
    sampler = RandomSampler(train_ds, generator=torch.Generator().manual_seed(SEED))
    loader = DataLoader(train_ds, batch_size=bsz, sampler=sampler)

    # AdamW with weight decay; warmup over first 10% of steps; linear decay after
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    total_steps    = len(loader) * NUM_EPOCHS
    warmup_steps   = int(WARMUP_RATIO * total_steps)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps
    )

    model.train()
    for epoch in range(NUM_EPOCHS):
        t0 = time.time()
        total_loss = 0
        for step, batch in enumerate(loader):
            input_ids = batch["input_ids"].to(device)
            attn = batch["attention_mask"].to(device)
            tok_type = batch.get("token_type_ids")
            tok_type = tok_type.to(device) if tok_type is not None else None
            labels = batch["label"].float().to(device) if is_regression else batch["label"].to(device)

            optimizer.zero_grad()
            out = model(input_ids=input_ids, attention_mask=attn, token_type_ids=tok_type, labels=labels)
            out.loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            total_loss += out.loss.item()
            if step % 200 == 0:
                print(f"    epoch {epoch+1}/{NUM_EPOCHS} step {step}/{len(loader)} loss={out.loss.item():.4f}")
        print(f"  [{task_name}] epoch {epoch+1} done in {time.time()-t0:.0f}s, avg loss {total_loss/len(loader):.4f}")

    os.makedirs(out_dir, exist_ok=True)
    model.save_pretrained(out_dir)
    tokenizer.save_pretrained(out_dir)
    print(f"  ✅ [{task_name}] fine-tuned checkpoint saved to {out_dir}\n")
    del model
    gc.collect()
    torch.cuda.empty_cache()

# ------------------------------------------------------------
# STAGE B: official quant_task_glue.py per task.
# --data_dir is the PARENT dir (script appends lowercase task_name itself).
# --model_dir is the PARENT dir containing {task_name}/ fine-tuned checkpoint.
# ------------------------------------------------------------

def run_ternarybert_quant(task_name):
    output_dir = f"{PROJECT_ROOT}/ternary_models/{task_name}"
    marker = f"{output_dir}/DONE.marker"
    if os.path.exists(marker):
        print(f"  [{task_name}] TernaryBERT quantization already completed, skipping.")
        return True
    os.makedirs(output_dir, exist_ok=True)

    cmd = (
        f"cd {TB_DIR} && python quant_task_glue.py "
        f"--data_dir {DATA_ROOT} "
        f"--model_dir {MODEL_DIR_ROOT} "
        f"--task_name {task_name} "
        f"--output_dir {output_dir} "
        f"--learning_rate {LEARNING_RATE} "
        f"--num_train_epochs {NUM_EPOCHS} "
        f"--train_batch_size {BATCH_SIZE} "
        f"--max_seq_length {MAX_SEQ_LEN} "
        f"--warmup_proportion {WARMUP_RATIO} "
        f"--weight_decay {WEIGHT_DECAY} "
        f"--seed {SEED} "
        f"--weight_bits 2 "
        f"--input_bits 8 "
        f"--pred_distill "
        f"--intermediate_distill "
        f"--save_quantized_model"
    )
    print(f"  [{task_name}] Running TernaryBERT QAT...")
    ret = subprocess.run(cmd, shell=True)
    if ret.returncode == 0:
        open(marker, "w").write("done")
        print(f"  ✅ [{task_name}] TernaryBERT quantization complete.\n")
        return True
    else:
        print(f"  ⚠️  [{task_name}] quant_task_glue.py failed (exit {ret.returncode}).\n")
        return False

# ------------------------------------------------------------
# RUN: small tasks first so you have real results quickly even if
# later (larger) tasks get interrupted by a Colab disconnect.
# ------------------------------------------------------------

OFFICIAL_TASKS = ["rte", "mrpc", "cola", "sts-b", "sst-2", "qnli", "mnli", "qqp"]

PROGRESS_FILE = f"{PROJECT_ROOT}/results/progress.json"
progress = json.load(open(PROGRESS_FILE)) if os.path.exists(PROGRESS_FILE) else {}

for task in OFFICIAL_TASKS:
    print(f"\n{'='*70}\n>>> TASK: {task}\n{'='*70}")
    if progress.get(task) == "done":
        print(f"⏭️  Already marked done, skipping.")
        continue
    finetune_bert_base(task)
    success = run_ternarybert_quant(task)
    progress[task] = "done" if success else "failed"
    json.dump(progress, open(PROGRESS_FILE, "w"))

print("\n\n" + "#"*70)
print("PIPELINE STATUS")
print("#"*70)
print(json.dumps(progress, indent=2))
print("\nNOTE: WNLI is intentionally excluded -- the official TernaryBERT")
print("script has no processor for it (verified in utils_glue.py), matching")
print("the original paper's own results table, which also omits WNLI.")
print(f"\nAll checkpoints saved under: {PROJECT_ROOT}")
print("Re-run this SAME cell after any disconnect to resume automatically.")

# ============================================================
# CELL 2 — Metrics extraction for the submission table
# Run this AFTER Cell 1 completes (or partially completes) tasks.
#
# WHY THIS CELL EXISTS: quant_task_glue.py (official script) only computes
# accuracy/F1/MCC/Pearson-Spearman internally, and writes NO results file
# to disk (verified: grepped the source, no results.txt/json writer exists).
# It also never measures Precision/Recall, model size, latency, throughput,
# or energy. This cell loads each saved quantized checkpoint and computes
# the full 9-column table by running our own eval pass.
#
# Loading approach verified against the real modeling_quant.py source:
#   - class is `BertForSequenceClassification` inside transformer/modeling_quant.py,
#     imported in the original script as QuantBertForSequenceClassification
#   - forward(input_ids, token_type_ids=None, attention_mask=None, labels=None)
#     returns (logits, attention_scores, encoded_layers) when labels=None
#   - from_pretrained(dir, num_labels=N) loads config.json + pytorch_model.bin
#     from the given directory (here: {output_dir}/{task}/quant/)
# ============================================================

import os, sys, time, json, csv
sys.path.insert(0, TB_DIR)  # so `from transformer...` imports resolve, if not already on path

# numpy/torch/random already imported in Cell 1; re-seed here so Cell 2
# produces deterministic eval ordering when run standalone.
import torch
import numpy as np
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

from torch.utils.data import DataLoader, SequentialSampler
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, matthews_corrcoef
from scipy.stats import pearsonr, spearmanr

from transformer.modeling_quant import BertForSequenceClassification as QuantBertForSequenceClassification
from transformer import BertTokenizer
from utils_glue import (
    ColaProcessor, MnliProcessor, MrpcProcessor, Sst2Processor,
    StsbProcessor, QqpProcessor, QnliProcessor, RteProcessor,
    convert_examples_to_features
)

PROCESSORS = {
    "cola": ColaProcessor, "mnli": MnliProcessor, "mrpc": MrpcProcessor,
    "sst-2": Sst2Processor, "sts-b": StsbProcessor, "qqp": QqpProcessor,
    "qnli": QnliProcessor, "rte": RteProcessor,
}
OUTPUT_MODES = {
    "cola": "classification", "mnli": "classification", "mrpc": "classification",
    "sst-2": "classification", "sts-b": "regression", "qqp": "classification",
    "qnli": "classification", "rte": "classification",
}
# Uniform 128 — matches training config; no per-task override
EVAL_MAX_SEQ_LEN = MAX_SEQ_LEN   # 128 from the Cell 1 constant

def evaluate_task(task_name):
    quant_dir = f"{PROJECT_ROOT}/ternary_models/{task_name}/quant"
    if not os.path.exists(f"{quant_dir}/pytorch_model.bin"):
        print(f"  [{task_name}] no saved quantized checkpoint found, skipping (was the run successful?).")
        return None

    processor = PROCESSORS[task_name]()
    output_mode = OUTPUT_MODES[task_name]
    label_list = processor.get_labels()
    num_labels = len(label_list)
    max_len = EVAL_MAX_SEQ_LEN   # uniform 128

    tokenizer = BertTokenizer.from_pretrained(quant_dir, do_lower_case=True)
    model = QuantBertForSequenceClassification.from_pretrained(quant_dir, num_labels=num_labels).to(device)
    model.eval()

    data_dir = f"{DATA_ROOT}/{task_name}"
    dev_file = "dev_matched" if task_name == "mnli" else "dev"
    eval_examples = (processor.get_dev_examples(data_dir) if task_name != "mnli"
                      else processor._create_examples(processor._read_tsv(os.path.join(data_dir, "dev_matched.tsv")), "dev_matched"))
    eval_features = convert_examples_to_features(eval_examples, label_list, max_len, tokenizer, output_mode)

    all_input_ids = torch.tensor([f.input_ids for f in eval_features], dtype=torch.long)
    all_input_mask = torch.tensor([f.input_mask for f in eval_features], dtype=torch.long)
    all_segment_ids = torch.tensor([f.segment_ids for f in eval_features], dtype=torch.long)
    if output_mode == "classification":
        all_label_ids = torch.tensor([f.label_id for f in eval_features], dtype=torch.long)
    else:
        all_label_ids = torch.tensor([f.label_id for f in eval_features], dtype=torch.float)

    eval_ds = torch.utils.data.TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)
    eval_loader = DataLoader(eval_ds, batch_size=BATCH_SIZE, sampler=SequentialSampler(eval_ds))

    # ---- Accuracy/F1/etc + latency/throughput in one pass ----
    all_preds, all_labels = [], []
    batch_times = []
    n_samples = 0
    with torch.no_grad():
        for batch in eval_loader:
            input_ids, input_mask, segment_ids, label_ids = [t.to(device) for t in batch]
            if device.type == "cuda":
                torch.cuda.synchronize()
            t0 = time.time()
            logits, _, _ = model(input_ids, segment_ids, input_mask)
            if device.type == "cuda":
                torch.cuda.synchronize()
            t1 = time.time()
            batch_times.append(t1 - t0)
            n_samples += input_ids.shape[0]
            all_preds.append(logits.detach().cpu().numpy())
            all_labels.append(label_ids.detach().cpu().numpy())

    all_preds = np.concatenate(all_preds, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)

    avg_latency_ms = (sum(batch_times) / len(batch_times)) * 1000
    throughput = n_samples / sum(batch_times)

    if output_mode == "regression":
        preds_flat = np.squeeze(all_preds)
        pearson = pearsonr(preds_flat, all_labels)[0]
        spearman = spearmanr(preds_flat, all_labels)[0]
        accuracy = (pearson + spearman) / 2  # reported as "Accuracy" proxy for regression task
        precision, recall = pearson, spearman
        f1 = 2 * pearson * spearman / (pearson + spearman + 1e-8)
    else:
        preds_cls = np.argmax(all_preds, axis=1)
        accuracy = accuracy_score(all_labels, preds_cls)
        avg_method = "binary" if num_labels == 2 else "macro"
        try:
            precision, recall, f1, _ = precision_recall_fscore_support(
                all_labels, preds_cls, average=avg_method, zero_division=0)
        except Exception:
            precision, recall, f1, _ = precision_recall_fscore_support(
                all_labels, preds_cls, average="macro", zero_division=0)

    mem_mb = os.path.getsize(f"{quant_dir}/pytorch_model.bin") / (1024 ** 2)

    energy_kwh = None
    try:
        from codecarbon import EmissionsTracker
        tracker = EmissionsTracker(log_level="error", save_to_file=False)
        tracker.start()
        with torch.no_grad():
            for batch in list(eval_loader)[:20]:
                input_ids, input_mask, segment_ids, label_ids = [t.to(device) for t in batch]
                model(input_ids, segment_ids, input_mask)
        emissions_kg = tracker.stop()
        energy_kwh = (emissions_kg * 1000 / 0.475) if emissions_kg else None  # rough back-calc, approximate
    except Exception:
        pass

    return {
        "Model name": "TernaryBERT (BERT-base)",
        "Memory Size (MB)": round(mem_mb, 2),
        "Latency (ms/batch)": round(avg_latency_ms, 2),
        "Accuracy": round(float(accuracy), 4),
        "Bits": 2,
        "Precision": round(float(precision), 4),
        "Recall": round(float(recall), 4),
        "F1-score": round(float(f1), 4),
        "Throughput (samples/sec)": round(throughput, 2),
        "Energy Consumption (kWh, approx)": round(energy_kwh, 6) if energy_kwh else "N/A",
    }

TASK_DISPLAY_NAMES = {
    "sst-2": "SST2", "qnli": "QNLI", "qqp": "QQP", "mnli": "MNLI",
    "mrpc": "MRPC", "sts-b": "STS-B", "rte": "RTE", "cola": "COLA",
}

all_results = {}
for task in ["sst-2", "qnli", "qqp", "mnli", "mrpc", "sts-b", "rte", "cola"]:
    print(f"\nEvaluating {task}...")
    try:
        r = evaluate_task(task)
        all_results[task] = r if r else {"error": "checkpoint not found / task not yet run"}
    except Exception as e:
        print(f"  ⚠️  Evaluation failed for {task}: {e}")
        all_results[task] = {"error": str(e)}

print("\n\n" + "#"*70)
print("FINAL RESULTS TABLE")
print("#"*70)
for task in ["sst-2", "qnli", "qqp", "wnli", "mnli", "mrpc", "sts-b", "rte", "cola"]:
    print(f"\nDataset name: {TASK_DISPLAY_NAMES.get(task, task.upper())}")
    if task == "wnli":
        print("  Model name\tMemory Size\tLatency\tAccuracy\tBits\tPrecision\tRecall\tF1-score\tThroughput\tEnergy Consumption")
        print("  NOT COVERED — official TernaryBERT script has no WNLI processor (verified in source).")
        print("  This matches the original paper's own results table, which also excludes WNLI.")
        continue
    r = all_results.get(task, {"error": "not run"})
    if "error" in r:
        print(f"  FAILED/NOT RUN: {r['error']}")
        continue
    headers = list(r.keys())
    print("  " + "\t".join(headers))
    print("  " + "\t".join(str(r[h]) for h in headers))

with open(f"{PROJECT_ROOT}/results/final_results.json", "w") as f:
    json.dump(all_results, f, indent=2)
print(f"\n\nSaved to {PROJECT_ROOT}/results/final_results.json")